"""initial migration

Revision ID: c7a194092daa
Revises: 
Create Date: 2017-09-24 18:36:19.174049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7a194092daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('notes', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
